name: ribs
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Luke Pighetti <lukepighetti@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  rxdart: ^0.22.2

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
